locals {

}

# A module that creates an AWS SSO Sym Flow that escalates Users to the 123456789 Account with PowerUser permissions
# in the Tenant A SSO instance.
module "tenant_a_power_user" {
  source = "./sso_flow"

  account_id         = ""
  permission_set_arn = ""
  sso_connector_settings = {
    cloud        = "aws",
    instance_arn = "",
    region       = "us-east-1",
    role_arn     = ""
  }
  sym_environment            = sym_environment.this
  sym_runtime_connector_role = aws_iam_role.sym_runtime_connector_role
  tenant_slug                = "tenant-foo"
}

resource "aws_iam_policy" "sso_assume_roles" {
  name = "${local.role_name}_SSOAssumeRoles"
  path = "/sym/"

  description = "This policy allows the Sym Runtime to assume roles in the /sym/ path in the given AWS SSO accounts."
  policy = jsonencode({
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Resource = [
        # TODO: This should be generated by a for-each
        #        "arn:aws:iam::${data.aws_caller_identity.tenant_a.sso_account_id}:role/sym/*",
        #        "arn:aws:iam::${data.aws_caller_identity.tenant_b.sso_account_id}:role/sym/*"
      ]
    }]
    Version = "2012-10-17"
  })
}

resource "aws_iam_role_policy_attachment" "attach_assume_roles_sso" {
  policy_arn = aws_iam_policy.sso_assume_roles.arn
  role       = aws_iam_role.sym_runtime_connector_role.name
}
